### ISSUE TITLE
support dark mode via css media queries?

### ISSUE THREAD

**Issue by kratsg** [matthewfeickert-talks/talk-chep-2024#11]
```css
.box {
  background: #dca;
  color: #731;
}
@media (prefers-color-scheme: dark) {
  .box {
    background: #753;
    color: #dcb;
    outline: 5px dashed #000;
  }
}
```
